[directory]
format = "[ ](bold #458588)[ $path ]($style)"
style = "bold #458588"

[character]
success_symbol = "[ ](bold #458588)[ ➜](bold green)"
error_symbol = "[ ](bold #458588)[ ➜](bold red)"

[cmd_duration]
format = "[󰔛 $duration]($style)"
style = "bg:none fg:#d79921"
show_notifications = false