[cursor]
blink_interval = 500

[cursor.style]
blinking = "On"
shape = "Beam"

# Default colors
[colors.primary]
background = '#{{base00}}'
foreground = '#{{base05}}'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '#{{base00}}'
cursor = '#{{base05}}'

# Normal colors
[colors.normal]
black = '#{{base00}}'
red = '#{{base08}}'
green = '#{{base0B}}'
yellow = '#{{base0A}}'
blue = '#{{base0D}}'
magenta = '#{{base0E}}'
cyan = '#{{base0C}}'
white = '#{{base05}}'

# Bright colors
[colors.bright]
black = "#{{base03}}"
blue = "#{{base0D}}"
cyan = "#{{base0C}}"
green = "#{{base0B}}"
magenta = "#{{base0E}}"
red = "#{{base08}}"
white = "#{{base07}}"
yellow = "#{{base0A}}"

[colors.cursor]
cursor = "#{{base05}}"
text = "#{{base00}}"

[colors.normal]
black = "#{{base00}}"
blue = "#{{base0D}}"
cyan = "#{{base0C}}"
green = "#{{base0B}}"
magenta = "#{{base0E}}"
red = "#{{base08}}"
white = "#{{base05}}"
yellow = "#{{base0A}}"

[colors.primary]
background = "#{{base00}}"
bright_foreground = "#{{base07}}"
foreground = "#{{base05}}"

[colors.selection]
background = "#{{base02}}"
text = "#{{base05}}"