[cursor]
blink_interval = 500

[cursor.style]
blinking = "On"
shape = "Beam"

# Default colors
[colors.primary]
background = '#1e1e2e'
foreground = '#cdd6f4'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '#1e1e2e'
cursor = '#cdd6f4'

# Normal colors
[colors.normal]
black = '#1e1e2e'
red = '#f38ba8'
green = '#a6e3a1'
yellow = '#f9e2af'
blue = '#89b4fa'
magenta = '#cba6f7'
cyan = '#94e2d5'
white = '#cdd6f4'

# Bright colors
[colors.bright]
black = "#45475a"
blue = "#89b4fa"
cyan = "#94e2d5"
green = "#a6e3a1"
magenta = "#cba6f7"
red = "#f38ba8"
white = "#b4befe"
yellow = "#f9e2af"

[colors.cursor]
cursor = "#cdd6f4"
text = "#1e1e2e"

[colors.normal]
black = "#1e1e2e"
blue = "#89b4fa"
cyan = "#94e2d5"
green = "#a6e3a1"
magenta = "#cba6f7"
red = "#f38ba8"
white = "#cdd6f4"
yellow = "#f9e2af"

[colors.primary]
background = "#1e1e2e"
bright_foreground = "#b4befe"
foreground = "#cdd6f4"

[colors.selection]
background = "#313244"
text = "#cdd6f4"